[package]
name = "rust-24days"
version = "0.1.0"
authors = ["s10myk4 <st4439@gmail.com>"]

[dependencies]
getopts = "~0.2.14"
num = "~0.1.36"
permutohedron = "~0.2.2"
primal = "~0.2.3"

[lib]
crate-type = ["cdylib"]
bench = false

[[bin]]
name = "day1"

[[bin]]
name = "day2"

